const fs = require("fs");

// this is generated by webpack + bazel and
// assumed to be in the container
const config = JSON.parse(fs.readFileSync("./route.manifest.json", "utf-8"));

config.CDN_HOST = process.env.CDN_HOST;

const getIdentifier = (path) =>
  path === "/" || typeof path === "undefined" ? "default" : path;

const getRemoteEntryScript = (path) => {
  const identifier = getIdentifier(path);
  const manifestIndex = path.substring(1) || "/";

  return `<script src="${process.env.CDN_HOST}/${identifier}/${
    config[manifestIndex]
  }">
    window.global.config=${JSON.stringify(config)}
  </script>`;
};

module.exports = ({ head = [""], path = "/" }) => {
  const identifier = getIdentifier(path);
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    ${head.join("\n")}
    ${getRemoteEntryScript(path)}
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`;
};
