const fs = require("fs");

// this is generated by webpack + bazel and
// assumed to be in the container
const config = JSON.parse(fs.readFileSync("./route.manifest.json").toString());

config.CDN_HOST = process.env.CDN_HOST;

module.exports = ({ head = [""] }) => `<!DOCTYPE html>
<html lang="en">
  <head>
    ${head.join("\n")}
  </head>
  <script>
    window.routeManifest = ${JSON.stringify(config)}
  </script>
  <body>
    <div id="root"></div>
  </body>
</html>
`;
