const fs = require("fs");

// this is generated by webpack + bazel and
// assumed to be in the container
const config = fs.readFileSync("./route.manifest.json").toString();

module.exports = ({ head = [""] }) => `<!DOCTYPE html>
<html lang="en">
  <head>
    ${head.join("\n")}
  </head>
  <script>
    window.routeManifest = ${JSON.stringify(JSON.parse(config))}
  </script>
  <body>
    <div id="root"></div>
  </body>
</html>
`;
