/** the server code that will render the HTML */

import getPageTemplate from "./getPageTemplate";
import fs from "fs";

// this is generated by webpack + bazel and
// assumed to be in the container
const config = fs.readFileSync("./config.json");
