const fs = require("fs");
const path = require("path");

// this is generated by webpack + bazel and
// assumed to be available
const routeManifest = JSON.parse(
  fs.readFileSync(path.join(__dirname, "route.manifest.json"), "utf-8")
);

module.exports = routeManifest;
