import { readFileSync } from "fs";
import { join } from "path";

export interface RouteManifest {
  [key: string]: string;
}

// this is generated by webpack + bazel and
// assumed to be available
export const routeManifest: RouteManifest = JSON.parse(
  readFileSync(join(__dirname, "route.manifest.json"), "utf-8")
);

export default routeManifest;
